[build]
target = "xtensa-esp32s3-espidf"
target-dir = "C:/t"

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
runner = "espflash flash --monitor --baud 921600 --port COM3 --partition-table partitions.csv"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
ESP_IDF_VERSION = "v5.5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "C:\\code2\\AMR2.0\\esp32s3xe-rust\\sdkconfig.defaults" }

# Uncomment this if you have moved the target dir by setting CARGO_TARGET_DIR or similar.
# Required for now due to embuild limitations.
CARGO_WORKSPACE_DIR = { value = "C:\\code2\\AMR2.0\\esp32s3xe-rust" }

